### ISSUE TITLE
Implement 'SetText' API

### ISSUE THREAD

**Issue by ekharkunov** [defold/extension-poco#5]
https://github.com/defold/extension-poco/blob/master/poco/lua/defold-poco.lua#L77

**Comment by AGulev** [comment]
I released a new version of Poco extension https://github.com/defold/extension-poco/releases/tag/1.0.2 (you don't need to update Defold to be able to use this functionality).

Using this version it's possible to use a few key event in one string.

The main idea behind Poco is emulation of user action.
In case with input text that means the following steps:

- click to the input text node;
- use HID layer for keyboard events imitation;
- hide keyboard;

Here is example how to do it for Druid:
https://github.com/defold/extension-poco/blob/97745377e16b2976228112bd66657cf47d198af9/examples/example_druid.py#L32-L35

### Click to the input text node
For click emulation we use regular `click` functionality:
>poco("bg").click() 

###  Use HID layer for keyboard events imitation
Here we use `keyevent` function:
>poco.agent.input.keyevent('any text')

This function takes a string, parse it char by char and imitate input for each char.
Also it's possible to use key codes for some special keys in brackets: 
https://github.com/defold/extension-poco/blob/c2efc3ecf176b01e7c99faad76c36740d873926d/poco/src/input_tables.cpp#L53-L183

###  Hide keyboard
It's important to call `gui.hide_keyboard()`. This functionality fully depends on implementation of input component. 
For example in case with Druid `ESC` call this function, that's why I add this key event in the end of the string:
>poco.agent.input.keyevent('test@mail.coo{KEY_BACKSPACE}m{KEY_ESC}') 

I tested it on iOS and Android (6.0, 10, 11) and everything works fine.

https://user-images.githubusercontent.com/2209596/152590860-f23f7576-a1a5-4929-9fbf-c97b5f25da1a.mov
